### PR TITLE
[Task] Adjust composer helper for TYPO3 v14

### LINKED ISSUE #507: Composer Helper not working with v14
Composer command is hidden when TYPO3 v14 is selected.

### PR DESCRIPTION
**Pull request by DavidBruchmann**
add version-number "14" for all system-extensions from the current repository, add new entries for styleguide and theme camino.
PR will fix #507

### CODE REVIEW

File: src/Service/ComposerPackagesService.php [hunk 1]
```diff
@@ -510,10 +540,18 @@ final class ComposerPackagesService
                 8,
             ],
         ],
+        [
+            'name'        => 'typo3/cms-styleguide',
+            'description' => 'TYPO3 extension to showcase TYPO3 Backend capabilities',
+            'versions' => [
+                14,
```
Comment (simonschaufi) [inline src/Service/ComposerPackagesService.php]: 13 is missing

Comment (DavidBruchmann) [reply src/Service/ComposerPackagesService.php]: no it wasn't included.  
I just did download the tar.gz and it's not inside.

Comment (DavidBruchmann) [reply src/Service/ComposerPackagesService.php]: beside that, @ohader created the version for v13 and he didn't add styleguide either.

Comment (simonschaufi) [reply src/Service/ComposerPackagesService.php]: ok, it's just that packagist has valid tags for typo3/cms-styleguide for v13

Comment (DavidBruchmann) [reply src/Service/ComposerPackagesService.php]: right, I don't mind if it's added but that's then an anachronistically change request which should also be realized with packaging.  
I'd propose to create an issue about it, if you think it might be desirable.

Comment (simonschaufi) [reply src/Service/ComposerPackagesService.php]: i personally don't really care, i just wanted to mention it as the styleguide should only be required for dev environments anyway.

Comment (ohader) [reply src/Service/ComposerPackagesService.php]: Euhm... `tar.gz`? We're talking about Composer packages here?!
Anyway, please drop styleguide since it is a dev-dependency.

File: src/Service/ComposerPackagesService.php [hunk 2]
```diff
@@ -668,6 +718,7 @@ final class ComposerPackagesService
             'typo3/cms-scheduler',
             'typo3/cms-seo',
             'typo3/cms-setup',
+            'typo3/cms-styleguide',
```
Comment (ohader) [inline src/Service/ComposerPackagesService.php]: As mentioned above, please drop styleguide

**Comment by DavidBruchmann** [comment]
EXT:styleguide is removed.
Don't know what I can do to make PHP Stan happy, let me know please how, if it's required.

**Comment by ohader** [comment]
The changes have been deployed to https://get.typo3.org/misc/composer/helper
Thanks for your contribution! 👍
